pipeline_name: payment_data_pipeline
version: "1.0"
description: End-to-end payment data pipeline

layers:
  bronze:
    enabled: true
    metadata_path: s3://bucket/config/metadata/bronze/
    max_parallel_workers: 5
    timeout_seconds: 3600
  
  silver:
    enabled: true
    metadata_path: s3://bucket/config/metadata/silver/
    max_parallel_workers: 3
    timeout_seconds: 3600
    depends_on:
      - bronze
  
  gold:
    enabled: true
    metadata_path: s3://bucket/config/metadata/gold/
    max_parallel_workers: 3
    timeout_seconds: 3600
    depends_on:
      - silver

execution:
  stop_on_layer_failure: true
  retry_failed_tasks: true
  max_retries: 3
  retry_delay_seconds: 60

monitoring:
  metrics_table: monitoring.pipeline_metrics
  log_level: INFO
  cloudwatch_enabled: true
  alert_on_failure: true
  alert_recipients:
    - data-eng@example.com

notifications:
  slack_webhook_secret: airflow/slack/webhook
  on_start: true
  on_complete: true
  on_failure: true
